// <copyright file="WeatherType.cs" company="Principal33">
// Copyright (c) Principal33. All rights reserved.
// </copyright>

namespace HelloWorldWebApp.Models
{
    public enum WeatherType
    {
        Freezing, Bracing, Chilly, Cool, Mild, Warm, Balmy, Hot, Sweltering, Scorching, Cloudy, LightRain, BrokenClouds, ModerateRain,
        OvercastClouds,
        ScatteredClouds,
        FewClouds,
        ClearSky,
        Tornado,
        Squalls,
        VolcanicAsh,
        Dust,
        Sand,
        Fog,
        SandDustWhirls,
        Haze,
        Mist,
        HeavyShowerSnow,
        ShowerSnow,
        LightShowerSnow,
        RainAndSnow,
        LightRainAndSnow,
        ShowerSleet,
        LightShowerSleet,
        Sleet,
        HeavySnow,
        LightSnow,
        RaggedShowerRain,
        HeavyIntensityShowerRain,
        ShowerRain,
        LightIntensityShowerRain,
        FreezingRain,
        ExtremeRain,
        VeryHeavyRain,
        HeavyIntensityRain,
        ShowerDrizzle,
        HeavyShowerRainAndDrizzle,
        ShowerRainAndDrizzle,
        HeavyIntensityDrizzleRain,
        DrizzleRain,
        LightIntensityDrizzleRain,
        HeavyIntensityDrizzle,
        Drizzle,
        LightIntensityDrizzle,
        ThunderstormWithHeavyDrizzle,
        ThunderstormWithDrizzle,
        ThunderstormWithLightDrizzle,
        RaggedThunderstorm,
        HeavyThunderstorm,
        Thunderstorm,
        LighThunderstorm,
        ThunderstormWithHeavyRain,
        ThunderstormWithRain,
        ThunderstormWithLightRain
    }
}